# -*- coding: utf-8 -*-
"""TitanicSurviverPredict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18XnKwoJOB9KTOZ3MX5HKvkqQqSgBbUqI
"""

import pandas as pd
import numpy as np
FIXED_RESULT = 1 # use random_state for fixed result

train_data = pd.read_csv('drive/My Drive/train_data/titanic_train.csv')
train_data.head()

train_data.isnull().sum()

# preprocessing
sex_mapping = {'male': 1, 'female': 0}
train_data['Sex'] = train_data['Sex'].map(sex_mapping)
train_data.head()

X = pd.DataFrame(train_data[['Pclass', 'Sex']])
y = pd.DataFrame(train_data.iloc[:, 1]) # Survived
print(X.shape)
print(y.shape)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=FIXED_RESULT)
print(X_train.shape)
print(X_test.shape)

# modeling
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state=FIXED_RESULT)
model.fit(X_train, y_train)

# prediction
print(model.score(X_test, y_test))